version: '2'

services:
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: pure_ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./data:/home/004"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: 004 
      FTP_USER_PASS: 1234
      FTP_USER_HOME: /home/004
    restart: always